### ISSUE TITLE
No checkboxes working inside modal

### ISSUE THREAD

**Issue by diqost** [adeptoas/sweet-modal-vue#10]
Hello there, if i place an <input type="checkbox"> inside sweet modal (content), i can not check/uncheck it.

**Comment by diqost** [comment]
I temporary fix this by adding to @click.stop (stop propagation) to all checkboxes, it seems that modal is cancel click events...

**Comment by bluefirex** [comment]
This has been fixed already in the newest version: https://github.com/adeptoas/sweet-modal-vue/issues/6
