### ISSUE TITLE
Add browser field in package.json

### ISSUE THREAD

**Issue by tjbenton** [adeptoas/sweet-modal-vue#11]
It makes it easier to pull in the dist files and not just the modules. It's useful for people who use unpkg.com or similar tools that look for the browser files https://github.com/defunctzombie/package-browser-field-spec

**Comment by bluefirex** [comment]
Added in 8666739c4736d5b13c1a3469389f223a1049d5a9, released in [v1.1.1](https://github.com/adeptoas/sweet-modal-vue/releases/tag/v1.1.1)
