### ISSUE TITLE
Provide option to disable pulse effect on blocking

### ISSUE THREAD

**Issue by dvatp** [adeptoas/sweet-modal-vue#12]
When the blocking prop is enabled and the user clicks outside the dialog a "pulse" effect occurs to provide some feedback that the user cannot dismiss the modal that way.

I recently ran into a case in which I was using a select menu whose options extended below the bottom of the dialog.  I am able to select all options without difficulty.  However, when I select a menu option that is below the bottom of the modal the click event gets through to SweetModal and it responds by pulsing the modal inappropriately.

I suppose one solution is to modify the select to trap the event so it is never passed on to SweetModal, but it would be nice if there was an option to control this kind of feedback in any case, as not all people like it or need it.

Please add a prop or other means to control the pulse effect while the blocking prop is present.  I believe it should be disabled by default.

**Comment by bluefirex** [comment]
Added in 069206184c65615643f01833b94ed0a357b73b59, released in [v1.1.1](https://github.com/adeptoas/sweet-modal-vue/releases/tag/v1.1.1)

**Comment by dvatp** [comment]
Awesome.  Thanks very much for working on this!
