### ISSUE TITLE
scss issue on laravel

### ISSUE THREAD

**Issue by denjaland** [adeptoas/sweet-modal-vue#13]
Hi,

I can't figure out how to get tihs to compile.
I tried getting this up in a L5.4 installation, but when I try to compile, I'm getting the error that he could not load the scss-loader.

Anyone knows how to have laravel mix know to use the sass loader for scss?
I have found some solutions, but none of them work.  The best I could get, is no errors, but an indefinitely running webpack procedure that doesn't spawn any errors, but seems to be stuck in an infinite loop.

Any assistance or thoughts would be much appreciated!

The plugin looks awesome by the way!

Cheers;
David.

**Comment by bluefirex** [comment]
Closed due to inactivity
