### ISSUE TITLE
Success icon with dark theme

### ISSUE THREAD

**Issue by deini** [adeptoas/sweet-modal-vue#16]
Not sure if I'm missing something but it looks like the icon `success` doesn't work with `modal-theme="dark"` 

Looks like this:
![screen shot 2017-05-17 at 9 20 53 pm](https://cloud.githubusercontent.com/assets/2752665/26183798/bc0ce47e-3b46-11e7-8510-87c2d71e6c7d.png)

**Comment by bluefirex** [comment]
Fixed in e2e3bcff5b807e9b3fde212db3c839ffa01d9e9a, released in [v1.1.1](https://github.com/adeptoas/sweet-modal-vue/releases/tag/v1.1.1)
