### ISSUE TITLE
Long modals don't scroll properly

### ISSUE THREAD

**Issue by cschweda** [adeptoas/sweet-modal-vue#20]
Long modals -- modals with a lot of content -- don't scroll properly. The page behind scrolls, but the modal itself doesn't. 

This is unusable with a big chunk of content due to this.

**Comment by bluefirex** [comment]
Fixed in 59584a02fcf2eeafd9d9cbc23926d1704634f05a, released in [v1.2.0](https://github.com/adeptoas/sweet-modal-vue/releases/tag/v1.2.0)
