### ISSUE TITLE
Register globally for single file components

### ISSUE THREAD

**Issue by coderjz** [adeptoas/sweet-modal-vue#25]
I'm using [single file components](https://vuejs.org/v2/guide/single-file-components.html) and would like to be able to register the modal component globally.  Can this be done?

I've tried in the main.js file to import SweetModal and then include it in `components: { SweetModal, App}`, but then if I try to use SweetModal I get the error 
`[Vue warn]: Unknown custom element: <sweet-modal> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`

If I however inside the component (.vue file) file src/components/mycomponent.vue I include the component, it works.

Note that I'm running sweet modal 1.1.10 as recommended by https://github.com/adeptoas/sweet-modal-vue/issues/22

**Comment by Fleeck** [comment]
@coderjz You should either register them globally by using `Vue.component`, or move them to mixin and include it globally via `Vue.mixin`. For further info read Vue API.

**Comment by bluefirex** [comment]
[v1.2.0](https://github.com/adeptoas/sweet-modal-vue/releases/tag/v1.2.0) has been released. Does it fix your issue?

**Comment by coderjz** [comment]
Sorry I've been on other projects and didn't get to this.  I'm going to close this for now as I don't have time to really look into this more.
