### ISSUE TITLE
Modal not centered

### ISSUE THREAD

**Issue by nicolasvahidzein** [adeptoas/sweet-modal-vue#26]
Hello,

i got the modal to work by changing the display to block as another user suggested but i cannot get the modal to center in the browser.

First off was i wrong to follow the css change from this user and second, should i be doing something different to center it?

**Comment by bluefirex** [comment]
It should already be centered. Can you attach a screenshot of how it looks right now and what changes to the css you did?

**Comment by bluefirex** [comment]
Closed due to inactivity
