### ISSUE TITLE
Failed to mount component: template or render function not defined.

### ISSUE THREAD

**Issue by lnhubbell** [adeptoas/sweet-modal-vue#30]
plugin fails to render given the configuration shown in this [stackoverflow post](https://stackoverflow.com/questions/45472485/failed-to-mount-component-template-or-render-function-not-defined).

Full code available in this [github repo](https://github.com/lnhubbell/vue-modal-debug).

**Comment by bluefirex** [comment]
This is now resolved and released in [v1.2.0](https://github.com/adeptoas/sweet-modal-vue/releases/tag/v1.2.0)
