### ISSUE TITLE
Import error with Webpack

### ISSUE THREAD

**Issue by nate250** [adeptoas/sweet-modal-vue#33]
When I follow the basic installation instructions, I get an error: `Uncaught SyntaxError: Unexpected token import` in `sweet-modal-view/src/main.js`. I believe this is because my build (based on a Vue 2.0 starter project) does not support transpiling node modules.

When I edit sweet-modal-vue's package.json to point to the dist folder as other vue component modules do, the exported object is empty.

**Comment by bluefirex** [comment]
Fixed in c05fb535b10cb39d2bfa17c218d198471a1e37da, released in [v2.0.0](https://github.com/adeptoas/sweet-modal-vue/releases/tag/v2.0.0)
