### ISSUE TITLE
Content blurred

### ISSUE THREAD

**Issue by enghelewa** [adeptoas/sweet-modal-vue#35]
Hi the contents of the modal is blurred due to animations. How to fix that?!

**Comment by bluefirex** [comment]
sweet-modal-vue doesn't have any blurring animations. Can you post a screenshot of the modal and the style properties from the dev tools?

**Comment by heribertusk** [comment]
@bluefirex : get blurred content too, but on my case its just happen on mobile view (on chrome dev tools). Seems okay on desktop display.

**Comment by enghelewa** [comment]
I think its related to other styles included in your website. If you viewed the examples online you will find it clear.

**Comment by mewcrow** [comment]
There is two identical components, one inside modal, other is not
![Снимок экрана 2019-11-28 в 12 11 51](https://user-images.githubusercontent.com/5108337/69793810-32bcd400-11da-11ea-8a28-6bee34d6fe23.png)
![Снимок экрана 2019-11-28 в 12 12 04](https://user-images.githubusercontent.com/5108337/69793811-33556a80-11da-11ea-86f6-edaf599e6ec6.png)
