### ISSUE TITLE
Unknown custom element

### ISSUE THREAD

**Issue by M0H3N** [adeptoas/sweet-modal-vue#36]
I'm using single file components and sweet-modal-vue ver 1.2 and Vue.js2 . 
I have tried the demo example but get this error : 
```
[Vue warn]: Unknown custom element: <SweetModal> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <Index> at src\components\home.vue
       <App> at src\App.vue
         <Root>
```

**Comment by bluefirex** [comment]
Fixed in c05fb535b10cb39d2bfa17c218d198471a1e37da, released in [v2.0.0](https://github.com/adeptoas/sweet-modal-vue/releases/tag/v2.0.0)
