### ISSUE TITLE
set width of modal?

### ISSUE THREAD

**Issue by cpfarher** [adeptoas/sweet-modal-vue#37]
Is there any way to set the width of the modal?, no props, no styles.....

**Comment by bluefirex** [comment]
There is no prop for the width, yet, but I think I can add one in an upcoming release.

**Comment by bluefirex** [comment]
Added in f6fe3e6e42dc001a750e52748f9e698012916231, released in [v2.0.0](https://github.com/adeptoas/sweet-modal-vue/releases/tag/v2.0.0)
