### ISSUE TITLE
Disable fullscreen on mobile

### ISSUE THREAD

**Issue by LudovicLangrand** [adeptoas/sweet-modal-vue#39]
Is it possible to disable the automatic fullscreen when the screen size is for mobile ?

**Comment by bluefirex** [comment]
Not yet, but I'll add it to the roadmap. Thanks for the suggestion!

**Comment by bluefirex** [comment]
Added in 5d00f2f546a591124ad78314671bf43023d6c8f2, released in [v2.0.0](https://github.com/adeptoas/sweet-modal-vue/releases/tag/v2.0.0)

**Comment by LudovicLangrand** [comment]
One last thing

In your release you say ;
"Support disabling mobile fullscreen (#39) by providing :enable-fullscreen-mobile="false" "

But it's :enable-mobile-fullscreen
