### ISSUE TITLE
Multiple modals, one on top of another?

### ISSUE THREAD

**Issue by mikamiel** [adeptoas/sweet-modal-vue#4]
Hi, sweet-modal-vue developers,
Is it possible to rise multiple modals one on top of another with the library?

**Comment by bluefirex** [comment]
Yes, that should be possible.

**Comment by mikamiel** [comment]
Thanks, i'll try it.

**Comment by bluefirex** [comment]
Nested Modals are now officially supported and documented in 4e8fe1256627976d32f626ce08ec5708db2809ae.

Released in [v1.1.0](https://github.com/adeptoas/sweet-modal-vue/releases/tag/v1.1.0)

**Comment by topclaudy** [comment]
The modals are not nested in the example provided. It's one modal being triggered from another modal. Check this issue for the desired feature: https://github.com/adeptoas/sweet-modal-vue/issues/54
