### ISSUE TITLE
Module build failed: Error: Couldn't find preset "es2015" relative to directory 

### ISSUE THREAD

**Issue by seifsay3d** [adeptoas/sweet-modal-vue#5]
I'm using Vue2, after I install the package I get this error.

**Comment by bluefirex** [comment]
Oh, it seems to be missing in the dependencies. For the time being you can install `babel-preset-es2015` manually by running `npm install babel-preset-es2015`. A proper fix is coming.

**Comment by bluefirex** [comment]
Fixed in 38be902f3766034d92b8c16c09d5f3dfba2a7948, released in [v1.1.0](https://github.com/adeptoas/sweet-modal-vue/releases/tag/v1.1.0)

**Comment by seifsay3d** [comment]
I cannot seem to be able to download this new version via npm.

**Comment by juanbrujo** [comment]
`warning "sweet-modal-vue@1.1.0" has unmet peer dependency "babel-preset-es2015@^6.0.0".`

had to install it manually
