### ISSUE TITLE
 Cannot find module "./components/SweetModal"

### ISSUE THREAD

**Issue by davodaslanifakor** [adeptoas/sweet-modal-vue#51]
hi i use SweetModal so npm install sweet-modal-vue and then
```import { SweetModal, SweetModalTab } from 'sweet-modal-vue'```
```
components: {
 SweetModal,
 SweetModalTab
}
```
![load](https://user-images.githubusercontent.com/14367811/34143732-6ee35014-e4a3-11e7-8ff8-a8d1db87a0a2.PNG)
how fix this ....??

**Comment by jamesgraham10** [comment]
I had to do this

`import SweetModal from 'sweet-modal-vue/src/components/SweetModal.vue'`

If you want the SweetModalTab

`import SweetModalTab from 'sweet-modal-vue/src/components/SweetModalTab.vue'`

**Comment by davodaslanifakor** [comment]
so yes fix this problem bu i have new problem....
![scss](https://user-images.githubusercontent.com/14367811/34196971-a55cc50e-e579-11e7-8258-3b2e9d11b338.PNG)
so i use that ```npm install --save-dev node-sass sass-loader```
but don't fix ....

**Comment by davodaslanifakor** [comment]
and remember i use less inside my project ....

**Comment by sharik709** [comment]
try this
```
import SweetModal from 'sweet-modal-vue/src/plugin';
```

**Comment by Maksimenka** [comment]
add this into  webpack.config
```   
resolve: {
      alias: {'vue$': 'vue/dist/vue.esm.js'},
      extensions: ['.js', '.vue'], // this string resolve your problem
}
