### ISSUE TITLE
Watch a modal when closed?

### ISSUE THREAD

**Issue by einnar82** [adeptoas/sweet-modal-vue#62]
How to watch a model when close?

**Comment by bluefirex** [comment]
What do you mean by "watching"? Detecting changes in display state?

**Comment by einnar82** [comment]
Yes exactly @bluefirex

**Comment by bluefirex** [comment]
The modal emits events "open" and "close", whenever its state changes. Just add your handler like this:

`<sweet-modal ... v-on:open="yourHandlerForOpenHere" v-on:close="yourHandlerForCloseHere">`
