### ISSUE TITLE
how can i change the modal position, not center in the window?

### ISSUE THREAD

**Issue by tengos** [adeptoas/sweet-modal-vue#74]
sir, how can i do this, like top: 30% in window? i need your help

**Comment by bluefirex** [comment]
You can use custom CSS for that on the .sweet-modal-box. There is no built-in support for that.

**Comment by tengos** [comment]
thank you for your replying

**Comment by Amaurgit** [comment]
Hello ! Same problem here.
Changing 

`.sweet-modal-box {top:38% !important;}
`

does'nt work :( any idea ?
I tried with .sweet-modal to !
Thank you :)
