### ISSUE TITLE
Wrong aligned title

### ISSUE THREAD

**Issue by christianmalek** [adeptoas/sweet-modal-vue#8]
As you can see in the picture below the title's position isn't vertically centered.

![image](https://cloud.githubusercontent.com/assets/2873986/24645704/9c87e5f8-1919-11e7-9945-c33024db1572.png)

Removing the margin rule solved the problem:
![image](https://cloud.githubusercontent.com/assets/2873986/24645752/c4433b88-1919-11e7-8582-674814be87ac.png)

**Comment by bluefirex** [comment]
Fixed in f1c9ab3b8e27fe433f76f3caa7fb7f664695fa9d, released in [v1.1.1](https://github.com/adeptoas/sweet-modal-vue/releases/tag/v1.1.1)

**Comment by christianmalek** [comment]
Thanks.

**Comment by ninogonzales** [comment]
I am having the same issue and I am on v2.0.0
