### ISSUE TITLE
Global Installation

### ISSUE THREAD

**Issue by Lavendar77** [adeptoas/sweet-modal-vue#92]
So, I tried installing this in my project, but the global installation from the [documentation](https://sweet-modal-vue.adepto.as/) is wrong.
```
import SweetModal from 'sweet-modal-vue/plugin.js'
Vue.use(SweetModal)
```
The above will generate errors after compilation.

Compiles with this
`import SweetModal from 'sweet-modal-vue/src/plugin.js'`

but gives an error when using the component
`<sweet-modal>This is a message</sweet-modal>`

**Comment by seriousmac** [comment]
`import VueFullPage from 'vue-fullpage.js'` works for me

**Comment by maparker21** [comment]
None of what you just put in here is relevant to the documentation. Where in the heck did "VueFullPage" come from? We simply want to include the modal globally as per the instructions provided, but that does't work

**Comment by Lavendar77** [comment]
I was wondering that myself. Anyway, has anyone been able to find a solution for the global configuration?

**Comment by seriousmac** [comment]
Try this `import SweetModal from 'sweet-modal-vue'`

**Comment by Lavendar77** [comment]
Nice trick! But it still does not work.

The import works, but `Vue.use(SweetModal)` gives a compilation error. 

Using the component `<sweet-modal>This is an alert.</sweet-modal>` is also not doing anything, just a normal HTML tag.

Thanks though @seriousmac 
I guess I am just going to have to settle for another plugin. 👋
